### PR TITLE
Fixed bug with strange LockTargetState value

### PR DESCRIPTION
**Pull request by gijoecool**

### CODE REVIEW

**Comment by rknabe** [comment]
This fix worked for me as well. Had an iPhone on 10.1 that was working before, but another iPhone on 10.2 was not. Both work now with this fix using Siri to lock and unlock doors.

**Comment by bkowalk** [comment]
This worked great! Siri finally works again. Thanks for the awesome work. Pretty please merge into master and I'll send cookies? :)

**Comment by pdlove** [comment]
I'm sorry. I thought this was put into master ages ago. I'll accept it now and update NPM tonight.

**Comment by bkowalk** [comment]
You're my hero.  Thanks!  This project is amazing--thanks for all the great work!

**Pull request merged**
