### PR TITLE
Master

### PR DESCRIPTION
**Pull request by tonesto7**
I resolved the constant errors by updating the deviceQuery() method.

I also added the set label input to allow people to change the name of
the smart app.
I updated the icon (keep if you like)

### CODE REVIEW

**Comment by rickybloomfield** [comment]
That icon makes sense, but I believe Apple owns the copyright, so probably shouldn't be included here.

**Comment by tonesto7** [comment]
I'm pretty sure that's not the icon apple uses... and it also doesn't contain the words homekit

**Comment by rickybloomfield** [comment]
That's the exact icon Apple uses: https://developer.apple.com/homekit/

And it even has "HomeKit" in the filename.

**Comment by tonesto7** [comment]
Lol... My bad...I completely forgot about the dev portal.  Either way does the icon really matter to apple?  Technically isn't Homebridge in general a no-no in apple's eyes?

**Comment by rickybloomfield** [comment]
Whether it matters is not for us to decide! I would recommend not including it in this GitHub repo.

**Comment by pdlove** [comment]
I want to accept Pull Request because it fills a hole, but we need to work on the icon.
I'm trying to not come out and say the smartapp is for Homebridge specifically because it can be used as a fairly universal json interface.
This icon is what I'd like to find: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/JSON_vector_logo.svg/2000px-JSON_vector_logo.svg.png

**Comment by tonesto7** [comment]
Ok i committed with the new icons you suggested.  At this time they are hosted on my Dropbox.

**Pull request merged**
